@extends('layouts.main')
@section('navhome', 'active')
@section('title', 'Home')

@section('content')
<h1> Welcome</h1>

<p>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quia, asperiores necessitatibus. Nesciunt, adipisci sapiente et itaque hic nemo nam quam minima ipsa eligendi qui, ratione voluptatum tempora! Corporis nihil quia dolores soluta, accusantium ullam sed non mollitia facilis harum vitae blanditiis exercitationem nulla ducimus porro ea sapiente autem debitis ex dolorum dolorem suscipit. Reiciendis fuga illo possimus. Atque quasi aliquid cupiditate nulla quibusdam ab culpa repellat autem blanditiis, officiis ea adipisci nihil, expedita deleniti. Minima odit, nostrum porro quo tempora, quasi ullam non mollitia assumenda cum fugit dolorem id necessitatibus ut perspiciatis quaerat iure molestias consectetur omnis vero beatae atque itaque fugiat! Et, praesentium doloribus ex odit aliquid laboriosam molestias nulla recusandae sint deserunt ipsa quia optio mollitia porro architecto, officia deleniti veniam incidunt! Explicabo odit voluptas pariatur culpa maxime nobis. Dolores accusamus error quos ipsa nemo maxime dolore qui pariatur incidunt minima assumenda nostrum libero sed deleniti atque natus nesciunt praesentium sapiente saepe harum, et labore dignissimos. Numquam, odio earum commodi inventore provident aperiam possimus corporis sapiente non, ab, ducimus ex voluptate voluptatum accusamus recusandae dolore magnam nobis aliquam aut sit omnis eum itaque blanditiis ipsam? Ipsum tenetur molestiae voluptates possimus maiores officia nulla consequuntur esse vitae, cupiditate doloribus placeat. Tempora eum itaque fuga? Veniam et assumenda cum aspernatur reprehenderit numquam est dolorem recusandae accusantium eaque, totam beatae nostrum molestiae, corporis minima dignissimos adipisci. Architecto quia inventore sint, assumenda consequatur reprehenderit eum eveniet voluptates quam quo nobis, provident distinctio atque, molestias iste animi! Quibusdam rem aspernatur expedita nisi reprehenderit modi inventore sint repellendus natus quisquam totam, nesciunt sequi eaque debitis soluta repudiandae assumenda asperiores earum possimus nam iure maxime! Sed dicta sint corrupti sapiente? Aliquam, ipsum modi? Dolorum maiores tenetur aliquid fugiat facilis nihil quos sint neque voluptatem. Quis sit rem maiores deserunt eius ratione odio et eos distinctio!
</p>
@endsection
